#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yelp-tools
Version  : 3.32.2
Release  : 10
URL      : https://download.gnome.org/sources/yelp-tools/3.32/yelp-tools-3.32.2.tar.xz
Source0  : https://download.gnome.org/sources/yelp-tools/3.32/yelp-tools-3.32.2.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: yelp-tools-bin = %{version}-%{release}
Requires: yelp-tools-data = %{version}-%{release}
Requires: yelp-tools-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : pkgconfig(yelp-xsl)

%description
ABOUT
=====
yelp-tools is a collection of scripts and build utilities to help create,
manage, and publish documentation for Yelp and the web. Most of the heavy
lifting is done by packages like yelp-xsl and itstool. This package just
wraps things up in a developer-friendly way.

%package bin
Summary: bin components for the yelp-tools package.
Group: Binaries
Requires: yelp-tools-data = %{version}-%{release}
Requires: yelp-tools-license = %{version}-%{release}

%description bin
bin components for the yelp-tools package.


%package data
Summary: data components for the yelp-tools package.
Group: Data

%description data
data components for the yelp-tools package.


%package dev
Summary: dev components for the yelp-tools package.
Group: Development
Requires: yelp-tools-bin = %{version}-%{release}
Requires: yelp-tools-data = %{version}-%{release}
Provides: yelp-tools-devel = %{version}-%{release}
Requires: yelp-tools = %{version}-%{release}

%description dev
dev components for the yelp-tools package.


%package license
Summary: license components for the yelp-tools package.
Group: Default

%description license
license components for the yelp-tools package.


%prep
%setup -q -n yelp-tools-3.32.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1562607875
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1562607875
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/yelp-tools
cp COPYING %{buildroot}/usr/share/package-licenses/yelp-tools/COPYING
cp COPYING.GPL %{buildroot}/usr/share/package-licenses/yelp-tools/COPYING.GPL
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/yelp-build
/usr/bin/yelp-check
/usr/bin/yelp-new

%files data
%defattr(-,root,root,-)
/usr/share/yelp-tools/templates/task.page
/usr/share/yelp-tools/xslt/comments.xsl
/usr/share/yelp-tools/xslt/mal-epub.xsl
/usr/share/yelp-tools/xslt/mal-files.xsl
/usr/share/yelp-tools/xslt/mal-license.xsl
/usr/share/yelp-tools/xslt/mal-ncx.xsl
/usr/share/yelp-tools/xslt/mal-opf.xsl
/usr/share/yelp-tools/xslt/mal-rng.xsl
/usr/share/yelp-tools/xslt/mal-status.xsl
/usr/share/yelp-tools/xslt/media.xsl

%files dev
%defattr(-,root,root,-)
/usr/share/aclocal/*.m4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/yelp-tools/COPYING
/usr/share/package-licenses/yelp-tools/COPYING.GPL
