#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yelp-tools
Version  : 41.0
Release  : 14
URL      : https://download.gnome.org/sources/yelp-tools/41/yelp-tools-41.0.tar.xz
Source0  : https://download.gnome.org/sources/yelp-tools/41/yelp-tools-41.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: yelp-tools-bin = %{version}-%{release}
Requires: yelp-tools-data = %{version}-%{release}
Requires: yelp-tools-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : lxml
BuildRequires : pkgconfig(yelp-xsl)

%description
ABOUT
=====
yelp-tools is a collection of scripts and build utilities to help create,
manage, and publish documentation for Yelp and the web. Most of the heavy
lifting is done by packages like yelp-xsl and itstool. This package just
wraps things up in a developer-friendly way.

%package bin
Summary: bin components for the yelp-tools package.
Group: Binaries
Requires: yelp-tools-data = %{version}-%{release}
Requires: yelp-tools-license = %{version}-%{release}

%description bin
bin components for the yelp-tools package.


%package data
Summary: data components for the yelp-tools package.
Group: Data

%description data
data components for the yelp-tools package.


%package dev
Summary: dev components for the yelp-tools package.
Group: Development
Requires: yelp-tools-bin = %{version}-%{release}
Requires: yelp-tools-data = %{version}-%{release}
Provides: yelp-tools-devel = %{version}-%{release}
Requires: yelp-tools = %{version}-%{release}

%description dev
dev components for the yelp-tools package.


%package license
Summary: license components for the yelp-tools package.
Group: Default

%description license
license components for the yelp-tools package.


%prep
%setup -q -n yelp-tools-41.0
cd %{_builddir}/yelp-tools-41.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632496954
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/yelp-tools
cp %{_builddir}/yelp-tools-41.0/COPYING %{buildroot}/usr/share/package-licenses/yelp-tools/91cdb2b9bee2de720d79abb2a88f00919c5de255
cp %{_builddir}/yelp-tools-41.0/COPYING.GPL %{buildroot}/usr/share/package-licenses/yelp-tools/b47456e2c1f38c40346ff00db976a2badf36b5e3
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/yelp-build
/usr/bin/yelp-check
/usr/bin/yelp-new

%files data
%defattr(-,root,root,-)
/usr/share/yelp-tools/templates/concept.duck
/usr/share/yelp-tools/templates/concept.page
/usr/share/yelp-tools/templates/guide.duck
/usr/share/yelp-tools/templates/guide.page
/usr/share/yelp-tools/templates/info.ducktype.include
/usr/share/yelp-tools/templates/info.mallard.include
/usr/share/yelp-tools/templates/reference.duck
/usr/share/yelp-tools/templates/reference.page
/usr/share/yelp-tools/templates/task.duck
/usr/share/yelp-tools/templates/task.page
/usr/share/yelp-tools/xslt/mal-ncx.xsl
/usr/share/yelp-tools/xslt/mal-opf.xsl
/usr/share/yelp-tools/xslt/mal-rng.xsl

%files dev
%defattr(-,root,root,-)
/usr/share/aclocal/*.m4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/yelp-tools/91cdb2b9bee2de720d79abb2a88f00919c5de255
/usr/share/package-licenses/yelp-tools/b47456e2c1f38c40346ff00db976a2badf36b5e3
